### PR TITLE
Add optional border

### PR DESCRIPTION
**Pull request by equeoDev**
I have modified the code in a way that an optional border is available.
The default props don't change the existing layout, only if borderWidth is given a border circle is added

### CODE REVIEW

**Comment by equeoDev** [comment]
All tests succeed here:

testcases

**Comment by trotzig** [comment]
Yeah, I checked out locally and saw things pass as well. All good!

**Comment by trotzig** [comment]
I'm waiting to hear from @lencioni (original author) before I merge this.

**Comment by equeoDev** [comment]
Sure, no problem at all for me.

**Pull request merged**
